version: "3.4"

x-common-volumes: &common-volumes
  - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json

x-common-variables: &common-variables
  MONGO_URI: mongodb://mongo:27017/merlinn-db
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/application_default_credentials.json

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: "."
      dockerfile: services/api/Dockerfile
    env_file:
      - services/api/.env
    environment:
      <<: *common-variables
      DATA_PROCESSOR_URL: http://data-processor:3002
    volumes: *common-volumes
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  slackbot:
    build:
      context: "."
      dockerfile: services/slackbot/Dockerfile
    env_file:
      - services/slackbot/.env.prod
    environment:
      <<: *common-variables
      API_BASE_URL: http://api:3000
    volumes: *common-volumes
    ports:
      - "3003:3003"
    depends_on:
      - mongo
  data-processor:
    build:
      context: "./services/data-processor"
    env_file:
      - services/data-processor/.env
    environment: *common-variables
    volumes: *common-volumes
    ports:
      - "3002:3002"
    depends_on:
      - mongo