version: "3"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: "."
      dockerfile: services/api/Dockerfile
    env_file:
      - services/api/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/merlinn-db
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/application_default_credentials.json
    volumes:
      # Google Cloud credentials file
      - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  slackbot:
    build:
      context: "."
      dockerfile: services/slackbot/Dockerfile
    env_file:
      - services/slackbot/.env.prod
    environment:
      # - MONGO_URI=mongodb://mongo:27017/merlinn-db
      # - API_BASE_URL=http://api:3000
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/application_default_credentials.json
    volumes:
      # Google Cloud credentials file
      - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json
    ports:
      - "3003:3003"
    depends_on:
      - mongo
  data-processor:
    build:
      context: "./services/data-processor"
    env_file:
      - services/data-processor/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/merlinn-db
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/application_default_credentials.json
    volumes:
      # Google Cloud credentials file
      - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json
    ports:
      - "3002:3002"
    depends_on:
      - mongo