version: "3"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data/dev/mongo:/data/db
    ports:
      - "27017:27017"
  api:
    build:
      context: "."
      dockerfile: services/api/Dockerfile
    env_file:
      - services/api/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/merlinn-db
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/application_default_credentials.json
    volumes:
      # Google Cloud credentials file
      - ~/.config/gcloud/application_default_credentials.json:/tmp/keys/application_default_credentials.json
    ports:
      - "3000:3000"
    depends_on:
      - mongo