service: merlinn-slackbot
runtime: nodejs20
env: standard

manual_scaling:
  instances: 1

env_variables:
  NODE_ENV: production
  API_BASE_URL: https://api.merlinn.co
  APP_TOKEN: $APP_TOKEN
  SLACK_BOT_TOKEN: $SLACK_BOT_TOKEN
  SLACK_SIGNING_SECRET: $SLACK_SIGNING_SECRET
