service: merlinn-api
runtime: nodejs20
env: standard

inbound_services:
  - warmup

env_variables:
  NODE_ENV: production
  GCLOUD_PROJECT: merlinn
  APP_URL: https://app.merlinn.co
  DATA_PROCESSOR_URL: https://merlinn-data-processor-dot-merlinn.nw.r.appspot.com
  AUTH0_AUDIENCE: https://api.merlinn.co/
  AUTH0_CLIENT_ID: OlN9gNhUElbyFMULgJhaVrO8gh5L6ZJV
  AUTH0_CLIENT_SECRET: s6p4rbzvpoM72HJaXY40Jqp8p1Qcjva-GAkRnzpB0qW1tSp0EP2SZELIOp-z-AQs
  AUTH0_ISSUER_BASE_URL: merlinn-prod.eu.auth0.com
  AUTH0_TEMPORARY_PASSWORD: DChdtAPYK3Mxsjo
  ENCRYPTION_SALT: 1234567890123456
  GH_APP_CLIENT_ID: Iv1.0e7a545acd90c287
  GH_APP_CLIENT_SECRET: c8ad69f5859d448d485a88628fa083ccd9a16a0d
  LANGFUSE_HOST: https://us.cloud.langfuse.com
  LANGFUSE_PROJECT_ID: clrngb9a60000ojkyw4222dzc
  LANGFUSE_PUBLIC_KEY: pk-lf-b10fa6be-2ff5-4d29-aba0-dfcc7377481c
  LANGFUSE_SECRET_KEY: sk-lf-2f60f985-0de4-4589-9216-803c084ddb64
  METADATA_ENCRYPTION_KEY: 5a802a57-efd6-4d31-b038-1c125a371fa5
  MONGO_URI: mongodb+srv://davidlasry696:bm-4JSk53dTRAd_@cluster0.xct5bdq.mongodb.net/merlinn-db?retryWrites=true&w=majority
  OPENAI_API_KEY: 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
  PAGERDUTY_CLIENT_ID: f59adf93-828e-4fb1-88ea-da8526e47ea3
  PAGERDUTY_CLIENT_SECRET: vO-5U_VJMQIVzGR8_2tCeKUFjT35h5cruorIxelFeEA
  PAGERDUTY_SECRET: yy/Dih7ZlJICv6a39rY3+AbLCvJ5hANdQijaUdS3wr1x0waQFMXMUw3X650OZeMf
  SENDGRID_API_KEY: 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
  SLACK_APP_TOKEN: xapp-1-A06FXKBLBNX-6564590486048-498cf30e4fa6f40bfccf1f90677f29b621889abfc7175bbf9a63d90fcc1e92b8
  SLACK_CLIENT_ID: 3889812999408.6541657691779
  SLACK_CLIENT_SECRET: eabeb5b93e0f1f848b2c3e3302f66552
  SLACK_EVENTS_CHANNEL_ID: C06H9MZ6GF6
  SLACK_NOTIFIER_TOKEN: xoxb-3889812999408-6608056662192-3P1hgMzJz87Wu3dDw5q8bEhl
  NOTION_CLIENT_ID: a40db1aa-46ab-409a-8fb8-b57d91702126
  NOTION_CLIENT_SECRET: secret_FTIV2pGfzfejvPIjzB631Gvflf6UkX2VaWqMSaFReok
  ATLASSIAN_CLIENT_ID: 1Ubv7b3taVd7pbHsJoMP12aYWxK1EqX4
  ATLASSIAN_CLIENT_SECRET: ATOAJVwPreX28b4WFLEhQpUiLGwM2Hhe3BQ0RLygdU2GOANYHDJMk5N7zdNzQ0vVVZZr5318CEDD
  PINECONE_API_KEY: 848ae0a5-ee44-4923-a84d-d1a671f72503
  MIXPANEL_PROJECT_TOKEN: 46d388c6f633ff01c70e99814a7f67c3
