service: merlinn-api
runtime: nodejs20
env: standard

inbound_services:
  - warmup

env_variables:
  NODE_ENV: production
  GCLOUD_PROJECT: merlinn
  APP_URL: https://app.merlinn.co
  DATA_PROCESSOR_URL: https://merlinn-data-processor-dot-merlinn.nw.r.appspot.com
  AUTH0_AUDIENCE: https://api.merlinn.co/
  AUTH0_CLIENT_ID: $AUTH0_CLIENT_ID
  AUTH0_CLIENT_SECRET: $AUTH0_CLIENT_SECRET
  AUTH0_ISSUER_BASE_URL: merlinn-prod.eu.auth0.com
  AUTH0_TEMPORARY_PASSWORD: $AUTH0_TEMPORARY_PASSWORD
  ENCRYPTION_SALT: $ENCRYPTION_SALT
  GH_APP_CLIENT_ID: $GH_APP_CLIENT_ID
  GH_APP_CLIENT_SECRET: $GH_APP_CLIENT_SECRET
  LANGFUSE_HOST: https://us.cloud.langfuse.com
  LANGFUSE_PROJECT_ID: $LANGFUSE_PROJECT_ID
  LANGFUSE_PUBLIC_KEY: $LANGFUSE_PUBLIC_KEY
  LANGFUSE_SECRET_KEY: $LANGFUSE_SECRET_KEY
  METADATA_ENCRYPTION_KEY: $METADATA_ENCRYPTION_KEY
  MONGO_URI: $MONGO_URI
  OPENAI_API_KEY: $OPENAI_API_KEY
  PAGERDUTY_CLIENT_ID: $PAGERDUTY_CLIENT_ID
  PAGERDUTY_CLIENT_SECRET: $PAGERDUTY_CLIENT_SECRET
  PAGERDUTY_SECRET: $PAGERDUTY_SECRET
  SENDGRID_API_KEY: $SENDGRID_API_KEY
  SLACK_APP_TOKEN: $SLACK_APP_TOKEN
  SLACK_CLIENT_ID: $SLACK_CLIENT_ID
  SLACK_CLIENT_SECRET: $SLACK_CLIENT_SECRET
  SLACK_EVENTS_CHANNEL_ID: $SLACK_EVENTS_CHANNEL_ID
  SLACK_NOTIFIER_TOKEN: $SLACK_NOTIFIER_TOKEN
  NOTION_CLIENT_ID: $NOTION_CLIENT_ID
  NOTION_CLIENT_SECRET: $NOTION_CLIENT_SECRET
  ATLASSIAN_CLIENT_ID: $ATLASSIAN_CLIENT_ID
  ATLASSIAN_CLIENT_SECRET: $ATLASSIAN_CLIENT_SECRET
  PINECONE_API_KEY: $PINECONE_API_KEY
  MIXPANEL_PROJECT_TOKEN: $MIXPANEL_PROJECT_TOKEN
